package controller;

public enum ControllerType {
    BOUNDSCONTROLLER, CONSTRUCTORCONTROLLER, DOWNLOADTOPOLOGYCONTROLLER, IMITATIONCONTROLLER, MAINCONTROLLER,
    MODELLERCONTROLLER, MOVECONTROLLER, SAVETOPOLOGYCONTROLLER, ADDCARCONTROLLER, ADDFUELCONTROLLER, DBWORKCONTROLLER
}
