package views;

public enum WindowType {
    BOUNDSWINDOW, CONSTRUCTORWINDOW, DOWNLOADTOPOLOGYWINDOW, DEVINFOWINDOW,
    SYSINFOWINDOW, IMITATIONWINDOW, MAINWINDOW, MODELLERWINDOW, SAVETOPOLOGYWINDOW,
    ADDCARWINDOW, ADDFUELWINDOW, DBWORKWINDOW
}
